// <auto-generated />
using System;
using BocciaCoaching.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BocciaCoaching.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251119042025_addStatisticTable")]
    partial class addStatisticTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Achievement", b =>
                {
                    b.Property<int>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AchievementId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("Ranked")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("AchievementId");

                    b.HasIndex("EventId");

                    b.ToTable("Achievement");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.AssessStrength", b =>
                {
                    b.Property<int>("AssessStrengthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AssessStrengthId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("AssessStrengthId");

                    b.HasIndex("TeamId");

                    b.ToTable("AssessStrength");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.AthletesToEvaluated", b =>
                {
                    b.Property<int>("AthletesToEvaluatedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AthletesToEvaluatedId"));

                    b.Property<int>("AssessStrengthId")
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.HasKey("AthletesToEvaluatedId");

                    b.HasIndex("AssessStrengthId");

                    b.HasIndex("AthleteId");

                    b.HasIndex("CoachId");

                    b.ToTable("AthletesToEvaluated");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.EvaluationDetailStrength", b =>
                {
                    b.Property<int>("EvaluationDetailStrengthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EvaluationDetailStrengthId"));

                    b.Property<int>("AssessStrengthId")
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int>("BoxNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observations")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ScoreObtained")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("TargetDistance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ThrowOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EvaluationDetailStrengthId");

                    b.HasIndex("AssessStrengthId");

                    b.HasIndex("AthleteId");

                    b.ToTable("EvaluationDetailStrength");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescriptionEvent")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LevelEventId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("NameEvent")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("LevelEventId");

                    b.HasIndex("UserId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.LevelEvent", b =>
                {
                    b.Property<int>("LevelEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LevelEventId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("NameLevel")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("LevelEventId");

                    b.ToTable("LevelEvent");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.LogError", b =>
                {
                    b.Property<int>("LogErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LogErrorId"));

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ModuleErrorId")
                        .HasColumnType("int");

                    b.HasKey("LogErrorId");

                    b.HasIndex("ModuleErrorId");

                    b.ToTable("LogError");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.ModuleError", b =>
                {
                    b.Property<int>("ModuleErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ModuleErrorId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ModuleErrorId");

                    b.ToTable("ModuleError");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.NotificationMessage", b =>
                {
                    b.Property<int>("NotificationMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationMessageId"));

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("NotificationMessageId");

                    b.HasIndex("AthleteId");

                    b.HasIndex("CoachId");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("NotificationMessage");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.NotificationType", b =>
                {
                    b.Property<int>("NotificationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("NotificationTypeId");

                    b.ToTable("NotificationType");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RolId");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Session");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.StrengthStatistics", b =>
                {
                    b.Property<int>("StrengthStatisticsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StrengthStatisticsId"));

                    b.Property<double>("AccuracyPercentage")
                        .HasColumnType("double");

                    b.Property<int>("AssessStrengthId")
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int>("EffectiveThrow")
                        .HasColumnType("int");

                    b.Property<double>("EffectivenessPercentage")
                        .HasColumnType("double");

                    b.Property<int>("FailedThrow")
                        .HasColumnType("int");

                    b.Property<double>("LongAccuracyPercentage")
                        .HasColumnType("double");

                    b.Property<double>("LongEffectivenessPercentage")
                        .HasColumnType("double");

                    b.Property<double>("LongThrow")
                        .HasColumnType("double");

                    b.Property<int>("LongThrowAccuracy")
                        .HasColumnType("int");

                    b.Property<double>("MediumAccuracyPercentage")
                        .HasColumnType("double");

                    b.Property<double>("MediumEffectivenessPercentage")
                        .HasColumnType("double");

                    b.Property<int>("MediumThrow")
                        .HasColumnType("int");

                    b.Property<int>("MediumThrowAccuracy")
                        .HasColumnType("int");

                    b.Property<double>("ShortAccuracyPercentage")
                        .HasColumnType("double");

                    b.Property<double>("ShortEffectivenessPercentage")
                        .HasColumnType("double");

                    b.Property<int>("ShortThrow")
                        .HasColumnType("int");

                    b.Property<int>("ShortThrowAccuracy")
                        .HasColumnType("int");

                    b.HasKey("StrengthStatisticsId");

                    b.HasIndex("AssessStrengthId");

                    b.HasIndex("AthleteId");

                    b.ToTable("StrengthStatistics");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<bool?>("Bc1")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Bc2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Bc3")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Bc4")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("NameTeam")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Pairs")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Teams")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TeamId");

                    b.HasIndex("CoachId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.TeamUser", b =>
                {
                    b.Property<int>("IdTeamUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTeamUser"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("IdTeamUser");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamUser");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Dni")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Seniority")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.UserRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRol");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Achievement", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.AssessStrength", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.AthletesToEvaluated", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.AssessStrength", "AssessStrength")
                        .WithMany()
                        .HasForeignKey("AssessStrengthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessStrength");

                    b.Navigation("Athlete");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.EvaluationDetailStrength", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.AssessStrength", "AssessStrength")
                        .WithMany()
                        .HasForeignKey("AssessStrengthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessStrength");

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Event", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.LevelEvent", "LevelEvent")
                        .WithMany()
                        .HasForeignKey("LevelEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LevelEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.LogError", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.ModuleError", "ModuleError")
                        .WithMany()
                        .HasForeignKey("ModuleErrorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuleError");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.NotificationMessage", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.User", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.NotificationType", "NotificationType")
                        .WithMany()
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Coach");

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Session", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.User", "User")
                        .WithOne("Session")
                        .HasForeignKey("BocciaCoaching.Models.Entities.Session", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.StrengthStatistics", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.AssessStrength", "AssessStrength")
                        .WithMany()
                        .HasForeignKey("AssessStrengthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessStrength");

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Team", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.User", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.TeamUser", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.UserRol", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.User", b =>
                {
                    b.Navigation("Session");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
