// <auto-generated />
using System;
using BocciaCoaching.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BocciaCoaching.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Achievement", b =>
                {
                    b.Property<Guid>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Ranked")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("AchievementId");

                    b.HasIndex("EventId");

                    b.ToTable("Achievement");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.AssessDirection", b =>
                {
                    b.Property<Guid>("AssessDirectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("AssessDirectionId");

                    b.HasIndex("CoachId");

                    b.HasIndex("TeamId");

                    b.ToTable("AssessDirection");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.AssessStrength", b =>
                {
                    b.Property<Guid>("AssessStrengthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("AssessStrengthId");

                    b.HasIndex("CoachId");

                    b.HasIndex("TeamId");

                    b.ToTable("AssessStrength");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.AthletesToEvaluated", b =>
                {
                    b.Property<Guid>("AthletesToEvaluatedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AssessStrengthId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("char(36)");

                    b.HasKey("AthletesToEvaluatedId");

                    b.HasIndex("AssessStrengthId");

                    b.HasIndex("AthleteId");

                    b.HasIndex("CoachId");

                    b.ToTable("AthletesToEvaluated");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.AthletesToEvaluatedDirection", b =>
                {
                    b.Property<Guid>("AthletesToEvaluatedDirectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AssessDirectionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("char(36)");

                    b.HasKey("AthletesToEvaluatedDirectionId");

                    b.HasIndex("AssessDirectionId");

                    b.HasIndex("AthleteId");

                    b.HasIndex("CoachId");

                    b.ToTable("AthletesToEvaluatedDirection");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.CoachMicrocycleTypeDistribution", b =>
                {
                    b.Property<Guid>("CoachMicrocycleTypeDistributionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("FisicaEspecial")
                        .HasColumnType("double");

                    b.Property<double>("FisicaGeneral")
                        .HasColumnType("double");

                    b.Property<Guid>("MicrocycleTypeId")
                        .HasColumnType("char(36)");

                    b.Property<double>("Psicologica")
                        .HasColumnType("double");

                    b.Property<double>("Tactica")
                        .HasColumnType("double");

                    b.Property<double>("Tecnica")
                        .HasColumnType("double");

                    b.Property<double>("Teorica")
                        .HasColumnType("double");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CoachMicrocycleTypeDistributionId");

                    b.HasIndex("CoachId");

                    b.HasIndex("MicrocycleTypeId");

                    b.ToTable("CoachMicrocycleTypeDistribution");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.DailyWellness", b =>
                {
                    b.Property<Guid>("DailyWellnessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AssessmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("char(36)");

                    b.Property<double>("AverageScore")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Fatigue")
                        .HasColumnType("int");

                    b.Property<int>("MusclePain")
                        .HasColumnType("int");

                    b.Property<string>("Observations")
                        .HasColumnType("longtext");

                    b.Property<int>("Sleep")
                        .HasColumnType("int");

                    b.Property<int>("Stress")
                        .HasColumnType("int");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("char(36)");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DailyWellnessId");

                    b.HasIndex("TeamId");

                    b.HasIndex("AthleteId", "AssessmentDate")
                        .IsUnique();

                    b.ToTable("DailyWellness");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.DirectionStatistics", b =>
                {
                    b.Property<Guid>("DirectionStatisticsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("AccuracyPercentage")
                        .HasColumnType("double");

                    b.Property<Guid>("AssessDirectionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("char(36)");

                    b.Property<double>("DeviatedLeftPercentage")
                        .HasColumnType("double");

                    b.Property<double>("DeviatedRightPercentage")
                        .HasColumnType("double");

                    b.Property<int>("EffectiveThrow")
                        .HasColumnType("int");

                    b.Property<double>("EffectivenessPercentage")
                        .HasColumnType("double");

                    b.Property<int>("FailedThrow")
                        .HasColumnType("int");

                    b.Property<double>("LongAccuracyPercentage")
                        .HasColumnType("double");

                    b.Property<int>("LongDeviatedLeft")
                        .HasColumnType("int");

                    b.Property<int>("LongDeviatedRight")
                        .HasColumnType("int");

                    b.Property<double>("LongEffectivenessPercentage")
                        .HasColumnType("double");

                    b.Property<double>("LongThrow")
                        .HasColumnType("double");

                    b.Property<int>("LongThrowAccuracy")
                        .HasColumnType("int");

                    b.Property<double>("MediumAccuracyPercentage")
                        .HasColumnType("double");

                    b.Property<int>("MediumDeviatedLeft")
                        .HasColumnType("int");

                    b.Property<int>("MediumDeviatedRight")
                        .HasColumnType("int");

                    b.Property<double>("MediumEffectivenessPercentage")
                        .HasColumnType("double");

                    b.Property<int>("MediumThrow")
                        .HasColumnType("int");

                    b.Property<int>("MediumThrowAccuracy")
                        .HasColumnType("int");

                    b.Property<double>("ShortAccuracyPercentage")
                        .HasColumnType("double");

                    b.Property<int>("ShortDeviatedLeft")
                        .HasColumnType("int");

                    b.Property<int>("ShortDeviatedRight")
                        .HasColumnType("int");

                    b.Property<double>("ShortEffectivenessPercentage")
                        .HasColumnType("double");

                    b.Property<int>("ShortThrow")
                        .HasColumnType("int");

                    b.Property<int>("ShortThrowAccuracy")
                        .HasColumnType("int");

                    b.Property<int>("TotalDeviatedLeft")
                        .HasColumnType("int");

                    b.Property<int>("TotalDeviatedRight")
                        .HasColumnType("int");

                    b.HasKey("DirectionStatisticsId");

                    b.HasIndex("AssessDirectionId");

                    b.HasIndex("AthleteId");

                    b.ToTable("DirectionStatistics");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.EvaluationDetailDirection", b =>
                {
                    b.Property<Guid>("EvaluationDetailDirectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AssessDirectionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("char(36)");

                    b.Property<int>("BoxNumber")
                        .HasColumnType("int");

                    b.Property<double>("CoordinateX")
                        .HasColumnType("double");

                    b.Property<double>("CoordinateY")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("DeviatedLeft")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DeviatedRight")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsCadence")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDirection")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsStrength")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTrajectory")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Observations")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ScoreObtained")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("TargetDistance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ThrowOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EvaluationDetailDirectionId");

                    b.HasIndex("AssessDirectionId");

                    b.HasIndex("AthleteId");

                    b.ToTable("EvaluationDetailDirection");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.EvaluationDetailStrength", b =>
                {
                    b.Property<Guid>("EvaluationDetailStrengthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AssessStrengthId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("char(36)");

                    b.Property<int>("BoxNumber")
                        .HasColumnType("int");

                    b.Property<double>("CoordinateX")
                        .HasColumnType("double");

                    b.Property<double>("CoordinateY")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCadence")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDirection")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsStrength")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTrajectory")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Observations")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ScoreObtained")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("TargetDistance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ThrowOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EvaluationDetailStrengthId");

                    b.HasIndex("AssessStrengthId");

                    b.HasIndex("AthleteId");

                    b.ToTable("EvaluationDetailStrength");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescriptionEvent")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LevelEventId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("NameEvent")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("EventId");

                    b.HasIndex("LevelEventId");

                    b.HasIndex("UserId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.LevelEvent", b =>
                {
                    b.Property<Guid>("LevelEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("NameLevel")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("LevelEventId");

                    b.ToTable("LevelEvent");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.LogError", b =>
                {
                    b.Property<Guid>("LogErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ModuleErrorId")
                        .HasColumnType("char(36)");

                    b.HasKey("LogErrorId");

                    b.HasIndex("ModuleErrorId");

                    b.ToTable("LogError");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Macrocycle", b =>
                {
                    b.Property<Guid>("MacrocycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AthleteName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MacrocycleId");

                    b.HasIndex("AthleteId");

                    b.HasIndex("CoachId");

                    b.HasIndex("TeamId");

                    b.ToTable("Macrocycle");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.MacrocycleEvent", b =>
                {
                    b.Property<Guid>("MacrocycleEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Level")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<Guid>("MacrocycleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MacrocycleEventId");

                    b.HasIndex("MacrocycleId");

                    b.ToTable("MacrocycleEvent");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.MacrocyclePeriod", b =>
                {
                    b.Property<Guid>("MacrocyclePeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MacrocycleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StageCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Weeks")
                        .HasColumnType("int");

                    b.HasKey("MacrocyclePeriodId");

                    b.HasIndex("MacrocycleId");

                    b.ToTable("MacrocyclePeriod");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Mesocycle", b =>
                {
                    b.Property<Guid>("MesocycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MacrocycleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Objective")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Weeks")
                        .HasColumnType("int");

                    b.HasKey("MesocycleId");

                    b.HasIndex("MacrocycleId");

                    b.ToTable("Mesocycle");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Microcycle", b =>
                {
                    b.Property<Guid>("MicrocycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HasPeakPerformance")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("LoadPercentage")
                        .HasColumnType("double");

                    b.Property<Guid>("MacrocycleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MesocycleName")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("MicrocycleTypeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("PeriodName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrainingDistribution")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("MicrocycleId");

                    b.HasIndex("MacrocycleId");

                    b.HasIndex("MicrocycleTypeId");

                    b.ToTable("Microcycle");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.MicrocycleDay", b =>
                {
                    b.Property<Guid>("MicrocycleDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MicrocycleId")
                        .HasColumnType("char(36)");

                    b.Property<double>("ThrowPercentage")
                        .HasColumnType("double");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MicrocycleDayId");

                    b.HasIndex("MicrocycleId");

                    b.ToTable("MicrocycleDay");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.MicrocycleType", b =>
                {
                    b.Property<Guid>("MicrocycleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ShortCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MicrocycleTypeId");

                    b.ToTable("MicrocycleType");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.MicrocycleTypeDayDefault", b =>
                {
                    b.Property<Guid>("MicrocycleTypeDayDefaultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CoachId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("MicrocycleTypeId")
                        .HasColumnType("char(36)");

                    b.Property<double>("ThrowPercentage")
                        .HasColumnType("double");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MicrocycleTypeDayDefaultId");

                    b.HasIndex("CoachId");

                    b.HasIndex("MicrocycleTypeId");

                    b.ToTable("MicrocycleTypeDayDefault");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.ModuleError", b =>
                {
                    b.Property<Guid>("ModuleErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ModuleErrorId");

                    b.ToTable("ModuleError");

                    b.HasData(
                        new
                        {
                            ModuleErrorId = new Guid("00000000-0000-0000-0000-0000000000a1"),
                            Description = "Módulo general",
                            Name = "General"
                        });
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.NotificationMessage", b =>
                {
                    b.Property<Guid>("NotificationMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<Guid>("NotificationTypeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("char(36)");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("NotificationMessageId");

                    b.HasIndex("NotificationTypeId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("NotificationMessage");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.NotificationType", b =>
                {
                    b.Property<Guid>("NotificationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("NotificationTypeId");

                    b.ToTable("NotificationType");

                    b.HasData(
                        new
                        {
                            NotificationTypeId = new Guid("00000000-0000-0000-0000-0000000000b1"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Notificación general",
                            Name = "General",
                            Status = true
                        },
                        new
                        {
                            NotificationTypeId = new Guid("00000000-0000-0000-0000-0000000000b2"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Invitación para unirse a un equipo",
                            Name = "Invitación a equipo",
                            Status = true
                        });
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AmountInCents")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FailureCode")
                        .HasColumnType("longtext");

                    b.Property<string>("FailureReason")
                        .HasColumnType("longtext");

                    b.Property<string>("Metadata")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("longtext");

                    b.Property<int?>("RefundedAmountInCents")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StripeInvoiceId")
                        .HasColumnType("longtext");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("longtext");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("PaymentId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Rol", b =>
                {
                    b.Property<Guid>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RolId");

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            RolId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Admin"
                        },
                        new
                        {
                            RolId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Coach"
                        },
                        new
                        {
                            RolId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Description = "Atleta"
                        });
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.SaremasAthleteEvaluation", b =>
                {
                    b.Property<Guid>("SaremasAthleteEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AthleteName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("SaremasEvalId")
                        .HasColumnType("char(36)");

                    b.HasKey("SaremasAthleteEvaluationId");

                    b.HasIndex("AthleteId");

                    b.HasIndex("SaremasEvalId");

                    b.ToTable("SaremasAthleteEvaluation");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.SaremasEvaluation", b =>
                {
                    b.Property<Guid>("SaremasEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double?>("AverageScore")
                        .HasColumnType("double");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("TotalScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SaremasEvaluationId");

                    b.HasIndex("CoachId");

                    b.HasIndex("TeamId");

                    b.ToTable("SaremasEvaluation");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.SaremasThrow", b =>
                {
                    b.Property<Guid>("SaremasThrowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("char(36)");

                    b.Property<double?>("ColorBallX")
                        .HasColumnType("double");

                    b.Property<double?>("ColorBallY")
                        .HasColumnType("double");

                    b.Property<string>("Diagonal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("DistanceToLaunchPoint")
                        .HasColumnType("double");

                    b.Property<double?>("EstimatedDistance")
                        .HasColumnType("double");

                    b.Property<string>("FailureTags")
                        .HasColumnType("longtext");

                    b.Property<double?>("LaunchPointX")
                        .HasColumnType("double");

                    b.Property<double?>("LaunchPointY")
                        .HasColumnType("double");

                    b.Property<string>("Observations")
                        .HasColumnType("longtext");

                    b.Property<Guid>("SaremasEvalId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ScoreObtained")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TechnicalComponent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ThrowNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("WhiteBallX")
                        .HasColumnType("double");

                    b.Property<double?>("WhiteBallY")
                        .HasColumnType("double");

                    b.HasKey("SaremasThrowId");

                    b.HasIndex("AthleteId");

                    b.HasIndex("SaremasEvalId");

                    b.ToTable("SaremasThrow");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Session");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.SessionPart", b =>
                {
                    b.Property<Guid>("SessionPartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("TrainingSessionId")
                        .HasColumnType("char(36)");

                    b.HasKey("SessionPartId");

                    b.HasIndex("TrainingSessionId");

                    b.ToTable("SessionPart");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.SessionSection", b =>
                {
                    b.Property<Guid>("SessionSectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsOwnDiagonal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumberOfThrows")
                        .HasColumnType("int");

                    b.Property<string>("Observation")
                        .HasColumnType("text");

                    b.Property<Guid>("SessionPartId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SessionSectionId");

                    b.HasIndex("SessionPartId");

                    b.ToTable("SessionSection");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.StrengthStatistics", b =>
                {
                    b.Property<Guid>("StrengthStatisticsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("AccuracyPercentage")
                        .HasColumnType("double");

                    b.Property<Guid>("AssessStrengthId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("char(36)");

                    b.Property<int>("EffectiveThrow")
                        .HasColumnType("int");

                    b.Property<double>("EffectivenessPercentage")
                        .HasColumnType("double");

                    b.Property<int>("FailedThrow")
                        .HasColumnType("int");

                    b.Property<double>("LongAccuracyPercentage")
                        .HasColumnType("double");

                    b.Property<double>("LongEffectivenessPercentage")
                        .HasColumnType("double");

                    b.Property<double>("LongThrow")
                        .HasColumnType("double");

                    b.Property<int>("LongThrowAccuracy")
                        .HasColumnType("int");

                    b.Property<double>("MediumAccuracyPercentage")
                        .HasColumnType("double");

                    b.Property<double>("MediumEffectivenessPercentage")
                        .HasColumnType("double");

                    b.Property<int>("MediumThrow")
                        .HasColumnType("int");

                    b.Property<int>("MediumThrowAccuracy")
                        .HasColumnType("int");

                    b.Property<double>("ShortAccuracyPercentage")
                        .HasColumnType("double");

                    b.Property<double>("ShortEffectivenessPercentage")
                        .HasColumnType("double");

                    b.Property<int>("ShortThrow")
                        .HasColumnType("int");

                    b.Property<int>("ShortThrowAccuracy")
                        .HasColumnType("int");

                    b.HasKey("StrengthStatisticsId");

                    b.HasIndex("AssessStrengthId");

                    b.HasIndex("AthleteId");

                    b.ToTable("StrengthStatistics");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Subscription", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAnnual")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTrial")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("NextRenewalDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int?>("PricePaidInCents")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("longtext");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("longtext");

                    b.Property<Guid>("SubscriptionTypeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("TrialEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("SubscriptionTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.SubscriptionType", b =>
                {
                    b.Property<Guid>("SubscriptionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("AnnualPriceInCents")
                        .HasColumnType("int");

                    b.Property<int?>("AthleteLimit")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Features")
                        .HasColumnType("longtext");

                    b.Property<bool>("HasAdvancedStatistics")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasPremiumChat")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MonthlyEvaluationLimit")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PriceInCents")
                        .HasColumnType("int");

                    b.Property<string>("StripeAnnualPriceId")
                        .HasColumnType("longtext");

                    b.Property<string>("StripeMonthlyPriceId")
                        .HasColumnType("longtext");

                    b.Property<string>("StripeProductId")
                        .HasColumnType("longtext");

                    b.Property<int?>("TeamLimit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SubscriptionTypeId");

                    b.ToTable("SubscriptionType");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Team", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool?>("Bc1")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Bc2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Bc3")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Bc4")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("NameTeam")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Pairs")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Teams")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TeamId");

                    b.HasIndex("CoachId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.TeamUser", b =>
                {
                    b.Property<Guid>("IdTeamUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("IdTeamUser");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamUser");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.TrainingSession", b =>
                {
                    b.Property<Guid>("TrainingSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MicrocycleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PhotoEvidence1")
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoEvidence2")
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoEvidence3")
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoEvidence4")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("ThrowPercentage")
                        .HasColumnType("double");

                    b.Property<int>("TotalThrowsBase")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TrainingSessionId");

                    b.HasIndex("MicrocycleId");

                    b.ToTable("TrainingSession");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Dni")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Seniority")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.UserRol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RolId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRol");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Achievement", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.AssessDirection", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.User", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.AssessStrength", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.User", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.AthletesToEvaluated", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.AssessStrength", "AssessStrength")
                        .WithMany()
                        .HasForeignKey("AssessStrengthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessStrength");

                    b.Navigation("Athlete");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.AthletesToEvaluatedDirection", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.AssessDirection", "AssessDirection")
                        .WithMany()
                        .HasForeignKey("AssessDirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessDirection");

                    b.Navigation("Athlete");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.CoachMicrocycleTypeDistribution", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.User", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.MicrocycleType", "MicrocycleType")
                        .WithMany()
                        .HasForeignKey("MicrocycleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("MicrocycleType");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.DailyWellness", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.User", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Athlete");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.DirectionStatistics", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.AssessDirection", "AssessDirection")
                        .WithMany()
                        .HasForeignKey("AssessDirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessDirection");

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.EvaluationDetailDirection", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.AssessDirection", "AssessDirection")
                        .WithMany()
                        .HasForeignKey("AssessDirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessDirection");

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.EvaluationDetailStrength", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.AssessStrength", "AssessStrength")
                        .WithMany()
                        .HasForeignKey("AssessStrengthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessStrength");

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Event", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.LevelEvent", "LevelEvent")
                        .WithMany()
                        .HasForeignKey("LevelEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LevelEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.LogError", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.ModuleError", "ModuleError")
                        .WithMany()
                        .HasForeignKey("ModuleErrorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuleError");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Macrocycle", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.User", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Coach");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.MacrocycleEvent", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.Macrocycle", "Macrocycle")
                        .WithMany("Events")
                        .HasForeignKey("MacrocycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Macrocycle");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.MacrocyclePeriod", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.Macrocycle", "Macrocycle")
                        .WithMany("Periods")
                        .HasForeignKey("MacrocycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Macrocycle");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Mesocycle", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.Macrocycle", "Macrocycle")
                        .WithMany("Mesocycles")
                        .HasForeignKey("MacrocycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Macrocycle");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Microcycle", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.Macrocycle", "Macrocycle")
                        .WithMany("Microcycles")
                        .HasForeignKey("MacrocycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.MicrocycleType", "MicrocycleType")
                        .WithMany()
                        .HasForeignKey("MicrocycleTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Macrocycle");

                    b.Navigation("MicrocycleType");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.MicrocycleDay", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.Microcycle", "Microcycle")
                        .WithMany("Days")
                        .HasForeignKey("MicrocycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Microcycle");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.MicrocycleTypeDayDefault", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.User", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BocciaCoaching.Models.Entities.MicrocycleType", "MicrocycleType")
                        .WithMany("DayConfigs")
                        .HasForeignKey("MicrocycleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("MicrocycleType");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.NotificationMessage", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.NotificationType", "NotificationType")
                        .WithMany()
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationType");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Payment", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.SaremasAthleteEvaluation", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.User", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.SaremasEvaluation", "SaremasEvaluation")
                        .WithMany("Athletes")
                        .HasForeignKey("SaremasEvalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("SaremasEvaluation");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.SaremasEvaluation", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.User", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.SaremasThrow", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.User", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.SaremasEvaluation", "SaremasEvaluation")
                        .WithMany("Throws")
                        .HasForeignKey("SaremasEvalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("SaremasEvaluation");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Session", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.User", "User")
                        .WithOne("Session")
                        .HasForeignKey("BocciaCoaching.Models.Entities.Session", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.SessionPart", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.TrainingSession", "TrainingSession")
                        .WithMany("Parts")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.SessionSection", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.SessionPart", "SessionPart")
                        .WithMany("Sections")
                        .HasForeignKey("SessionPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionPart");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.StrengthStatistics", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.AssessStrength", "AssessStrength")
                        .WithMany()
                        .HasForeignKey("AssessStrengthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessStrength");

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Subscription", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.SubscriptionType", "SubscriptionType")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriptionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Team", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.User", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.TeamUser", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.TrainingSession", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.Microcycle", "Microcycle")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("MicrocycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Microcycle");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.UserRol", b =>
                {
                    b.HasOne("BocciaCoaching.Models.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BocciaCoaching.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Macrocycle", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Mesocycles");

                    b.Navigation("Microcycles");

                    b.Navigation("Periods");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Microcycle", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.MicrocycleType", b =>
                {
                    b.Navigation("DayConfigs");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.SaremasEvaluation", b =>
                {
                    b.Navigation("Athletes");

                    b.Navigation("Throws");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.SessionPart", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.Subscription", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.SubscriptionType", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.TrainingSession", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("BocciaCoaching.Models.Entities.User", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Session");

                    b.Navigation("Subscriptions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
